/*+-------------------------------------------------------------------+
  |  <DOC>                                                            |
  |  <NAME>    t_spawn()                                              |
  |  <AUTHOR>  John L. Foster                                         |
  |  <DATE>    November 14, 1988                                      |
  |  <LEVEL>   TM                                                     |
  |  <GLOBAL>  TM_master                                              |
  |                                                                   |
  |  <PARAM>   some_ocb    OCB *      INPUT  Any object control block |
  |  <PARAM>   packet      string     INPUT  Packet of OCD's that are |
  |                                           modified for reiterative|
  |  <PARAM>   state       sint       INPUT  State ID                 |
  |  <PARAM>   result_str  string *   INOUT  Pointer to a string where|
  |                                           error messages and other|
  |                                           communicated data will  |
  |                                           go.                     |
  |                                                                   |
  |  <PURPOSE> Send an object or packet to the Master Server.         |
  |            If this server is not the Master Server then the object|
  |            is sent to the Master Server for linking.              |
  |                                                                   |
  |            If the object is sent to a MS or DS and the link flag  |
  |            is set, mark the object as a remote object to indicate |
  |            it no longer belongs on this server.                   |
  |                                                                   |
  |  <OUTPUT>  sint      result code either generated by this routine |
  |                      locally or remotely.                         |
  |                                                                   |
  |  <CALLS>   t_send(), t_waitc(), t_m_obj(), s_len(), except()      |
  |  <MODS>                                                           |
  |            Mar 4, 1989    JF    Added REMOTE object flag setting. |
  |  </DOC>                                                           |
  +-------------------------------------------------------------------+*/
#include "defs.h"
#include "str.h"
#include "osk.h"
#include "debug.h"
#include "obj.h"
#include "obj_prim.h"
#include "exc.h"
#include "tm.h"




sint     t_spawn( some_ocb, packet, state, result_str )

OCB             * some_ocb;
string            packet;
sint              state;
void            * result_str;

{

   sint      rc             =        0;
   hword     command        = OCD_SEND,
             flags          =        0;
   boolean   ok_to_link     =     TRUE;







   if( s_len( packet ) > 0 )
   {


      flags |= OK_TO_LINK_OBJECT;

      rc = t_send( TM_master->MS, OCD_SEND, flags, state, packet );
      if( rc != 0 )
      {

         except( rc, CONTROL_ERROR, TM_master->MS, S_NULL, S_NULL,
                                                   S_NULL, S_NULL );

      }
      else
      {

         rc = t_waitc( TM_master->MS, result_str );

      }
   }
   else
   {

      rc = t_m_obj( TM_master->MS, some_ocb, result_str, ok_to_link, state );

   }

   if( rc == 0  && TM_master->usrtype == USER_SERVER && ok_to_link )
   {

      obj_set_flag( some_ocb, OBJ_REMOTE );

   }



   return(rc);

}
