/*+-------------------------------------------------------------------+
  |  <DOC>                                                            |
  |  <NAME>    form_i.h    ---  HEADER FILE                           |
  |  <AUTHOR>  Nestor R. Voronka                                      |
  |  <DATE>    March 21, 1988                                         |
  |  <LEVEL>   FORMS                                                  |
  |  <PURPOSE> To include both internal and common FORMS headers.     |
  |  <ERRORS>                                                         |
  |  <LIMITS>                                                         |
  |  <MODS>    NV  Mar 21 88  Restructure forms header files to       |
  |                           internal/external/common structure.     |
  |  </DOC>                                                           |
  +-------------------------------------------------------------------+*/

#include "form_com.h"
#include "form_i_i.h"
#include "form_i_x.h"
#include "form_pf.h"
