/*+-------------------------------------------------------------------+
  |  <DOC>                                                            |
  |  <NAME>    form_i_x.h  ---  HEADER FILE                           |
  |  <AUTHOR>  Nestor R. Voronka                                      |
  |  <DATE>    March 21, 1988                                         |
  |  <LEVEL>   FORMS                                                  |
  |  <PURPOSE> To provide external declarations to internal forms     |
  |            functions.                                             |
  |  <ERRORS>                                                         |
  |  <LIMITS>                                                         |
  |  <MODS>    NV  Mar 21 88  Restructure forms header files to       |
  |                           internal/external/common structure.     |
  |  </DOC>                                                           |
  +-------------------------------------------------------------------+*/
#include "formp_x.h"
#include "formf_x.h"
#include "formd_x.h"
#include "form_x.h"
