/*+-------------------------------------------------------------------+
  |  <DOC>                                                            |
  |  <NAME>    form.h      ---  HEADER FILE                           |
  |  <AUTHOR>  Nestor R. Voronka                                      |
  |  <DATE>    March 21, 1988                                         |
  |  <LEVEL>   FORMS                                                  |
  |  <PURPOSE> To include both external and common header files.      |
  |  <ERRORS>                                                         |
  |  <LIMITS>                                                         |
  |  <MODS>    NV  Mar 21 88  Restructure forms header files to       |
  |                           internal/external/common structure.     |
  |  </DOC>                                                           |
  +-------------------------------------------------------------------+*/

#ifndef FORM_H_INCLUDED

#define FORM_H_INCLUDED 1

#include "form_com.h"
#include "form_x.h"
#include "form_pf.h"


#endif
