/*+-------------------------------------------------------------------+
  |                                                                   |
  |  :NAME.    GKS Header                                             |
  |                                                                   |
  |  :AUTHOR.  John L. Foster                                         |
  |                                                                   |
  |  :DATE.    November 7, 1988                                       |
  |                                                                   |
  |  :LEVEL.   GKS                                                    |
  |                                                                   |
  |  :PURPOSE. Determine the proper inclusions for the GKS Level.     |
  |                                                                   |
  |  :END.                                                            |
  |                                                                   |
  +-------------------------------------------------------------------+*/
#ifndef GKS_H_INCLUDED

#define GKS_H_INCLUDED 1

#include "GKS_COMM.H"
#include "GKS_I.H"
#include "GKS_I_I.H"
#include "GKS_X.H"
#include "GV_COMM.H"

#endif
