/*********************************************************************


:NAME.    GKS_I.H
:LEVEL.   GKS internal
:DATE.    June 23, 187
:AUTHOR.  Kenneth Liang

:PURPOSE.

     This header file will be included in internal GKS modules. It
     includes:

     gks_comm.h     definitions of GKS macro's and data structures
                    used by both GKS external and internal routines

     gks_i_i.h      declarations of internal GKS routines which are
                    called only by GKS routines.

:MODS.

:END.



*********************************************************************/


#include "gv_comm.h"
#include "gks_comm.h"
#include "gks_i_i.h"
