/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
:NAME.                  ISF H

:LEVEL.                 ISCF

:AUTHOR.                Sal Johar

:DATE.                  02/11/89

:PURPOSE.

:MODS.
                        Moved routines out of this header file into
                        ISF_X H

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef ISF_H_INCLUDED

#define ISF_H_INCLUDED 1
#include "isf_x.h"

#endif
