/* NOTICE:  ALTERATIONS TO THIS FILE WILL BE DISCARDED!               */
/* It is automatically created by ISVGEN EXEC.                        */
/*  Created from "ENGLISH ISV     B" on 89-11-27 at 09:31.            */
#define ISV_UNKNOWN  ((isv)   1) /* Unknown ISV requested             */
#define ISV_USER     ((isv)  11) /* User                              */
#define ISV_GROUP    ((isv)  12) /* Group                             */
#define ISV_NTDR     ((isv)  13) /* Network Directory                 */
#define ISV_CONF     ((isv)  14) /* Conference                        */
#define ISV_CC       ((isv)  15) /* Conference Comment                */
#define ISV_MMSG     ((isv)  16) /* Mail Message                      */
#define ISV_NOTIF    ((isv)  17) /* Notification                      */
#define ISV_SOIDI    ((isv)  18) /* System Object Identification Inde */
#define ISV_PSI      ((isv)  19) /* Priciple System Index             */
#define ISV_SKI      ((isv)  20) /* System Keyword Index              */
#define ISV_SAI      ((isv)  21) /* System Author Index               */
#define ISV_SDTI     ((isv)  22) /* System Date/Time Index            */
#define ISV_CRI      ((isv)  23) /* Conference Root Index             */
#define ISV_SDI      ((isv)  24) /* System Directory Index            */
#define ISV_SHI      ((isv)  25) /* System Help Index                 */
#define ISV_SNI      ((isv)  26) /* System Name Index                 */
#define ISV_MEMB     ((isv)  27) /* Membership                        */
#define ISV_SERRI    ((isv)  28) /* System Error Index                */
#define ISV_SFI      ((isv)  29) /* System Forms Index                */
#define ISV_LIST     ((isv)  30) /* List                              */
#define ISV_ACTIVITY ((isv)  31) /* Activity                          */
#define ISV_TICKET   ((isv)  32) /* Ticket                            */
#define ISV_CONTENTS ((isv)  33) /* Contents                          */
#define ISV_READ     ((isv)  41) /* Read                              */
#define ISV_QUESTION ((isv)  42) /* Question                          */
#define ISV_SELECTIO ((isv)  43) /* Selection                         */
#define ISV_RESPONSE ((isv)  44) /* Response                          */
#define ISV_PROBLEM  ((isv)  45) /* Problem                           */
#define ISV_VOTE     ((isv)  46) /* Vote                              */
#define ISV_QUIZ     ((isv)  47) /* Quiz                              */
#define ISV_FIRSTON  ((isv)  61) /* First Signon                      */
#define ISV_ID       ((isv)  62) /* Id                                */
#define ISV_LABEL    ((isv)  63) /* Label                             */
#define ISV_CASUAL   ((isv)  80) /* Casual                            */
#define ISV_EXPERT   ((isv)  81) /* Experienced                       */
#define ISV_POWER    ((isv)  82) /* Power                             */
#define ISV_CONSOLE  ((isv)  98) /* Console                           */
#define ISV_PRINTER  ((isv)  99) /* Printer                           */
#define ISV_JAN      ((isv) 101) /* January                           */
#define ISV_FEB      ((isv) 102) /* February                          */
#define ISV_MAR      ((isv) 103) /* March                             */
#define ISV_APR      ((isv) 104) /* April                             */
#define ISV_MAY      ((isv) 105) /* May                               */
#define ISV_JUN      ((isv) 106) /* June                              */
#define ISV_JUL      ((isv) 107) /* July                              */
#define ISV_AUG      ((isv) 108) /* August                            */
#define ISV_SEP      ((isv) 109) /* September                         */
#define ISV_OCT      ((isv) 110) /* October                           */
#define ISV_NOV      ((isv) 111) /* November                          */
#define ISV_DEC      ((isv) 112) /* December                          */
#define ISV_AM       ((isv) 113) /* AM                                */
#define ISV_PM       ((isv) 114) /* PM                                */
#define ISV_MON      ((isv) 121) /* Monday                            */
#define ISV_TUE      ((isv) 122) /* Tuesday                           */
#define ISV_WED      ((isv) 123) /* Wednesday                         */
#define ISV_THU      ((isv) 124) /* Thursday                          */
#define ISV_FRI      ((isv) 125) /* Friday                            */
#define ISV_SAT      ((isv) 126) /* Saturday                          */
#define ISV_SUN      ((isv) 127) /* Sunday                            */
#define ISV_VIEW     ((isv) 130) /* View                              */
#define ISV_SCAN     ((isv) 131) /* Scan                              */
#define ISV_CREATE   ((isv) 132) /* Create                            */
#define ISV_MODIFY   ((isv) 133) /* Modify                            */
#define ISV_REMOVE   ((isv) 134) /* Remove                            */
#define ISV_REVIEW   ((isv) 135) /* Review                            */
#define ISV_FIND     ((isv) 136) /* Find                              */
#define ISV_JOIN     ((isv) 137) /* Join                              */
#define ISV_RECEIVE  ((isv) 138) /* Receive                           */
#define ISV_DO       ((isv) 139) /* Do                                */
#define ISV_ORGANIZE ((isv) 140) /* Organize                          */
#define ISV_GET      ((isv) 141) /* Get                               */
#define ISV_LINK     ((isv) 142) /* Link                              */
#define ISV_PERSONAL ((isv) 150) /* Personal                          */
#define ISV_BUSINESS ((isv) 151) /* Business                          */
#define ISV_URGENT   ((isv) 152) /* Urgent                            */
#define ISV_ACTION   ((isv) 153) /* Action                            */
#define ISV_INTEREST ((isv) 154) /* Interest                          */
#define ISV_MONITORI ((isv) 155) /* Monitoring                        */
#define ISV_NEW      ((isv) 160) /* New                               */
#define ISV_OLD      ((isv) 161) /* Old                               */
#define ISV_MARKED   ((isv) 162) /* Marked                            */
#define ISV_YES      ((isv) 163) /* Yes                               */
#define ISV_NO       ((isv) 164) /* No                                */
#define ISV_OPEN     ((isv) 165) /* Open                              */
#define ISV_FROZEN   ((isv) 166) /* Frozen                            */
#define ISV_CLOSED   ((isv) 167) /* Closed                            */
#define ISV_ALL      ((isv) 168) /* All                               */
#define ISV_LAST     ((isv) 169) /* Last                              */
#define ISV_ATTACHED ((isv) 170) /* Attached                          */
#define ISV_DONE     ((isv) 171) /* Done                              */
#define ISV_UNDONE   ((isv) 172) /* Undone                            */
#define ISV_REQUIRED ((isv) 173) /* Required                          */
#define ISV_OPTIONAL ((isv) 174) /* Optional                          */
#define ISV_TEMPORAR ((isv) 175) /* Temporary                         */
#define ISV_OKAY     ((isv) 176) /* Okay                              */
#define ISV_REVISION ((isv) 177) /* Revision                          */
#define ISV_DRAFT    ((isv) 178) /* Draft                             */
#define ISV_NOTEXT   ((isv) 179) /* NoText                            */
#define ISV_QUIT     ((isv) 180) /* Quit                              */
#define ISV_ABANDON  ((isv) 181) /* Abandon                           */
#define ISV_FORWARD  ((isv) 182) /* Forward                           */
#define ISV_BACKWARD ((isv) 183) /* Backward                          */
#define ISV_HELP     ((isv) 184) /* Help                              */
#define ISV_CONFIRM  ((isv) 185) /* Confirm                           */
#define ISV_DISCUSSI ((isv) 190) /* Discussion                        */
#define ISV_SEMINAR  ((isv) 191) /* Seminar                           */
#define ISV_PROJECT  ((isv) 192) /* Project                           */
#define ISV_EXCHANGE ((isv) 193) /* Exchange                          */
#define ISV_COMPOSIT ((isv) 194) /* Composition                       */
#define ISV_DATASET  ((isv) 195) /* Data Set                          */
#define ISV_SIMULATI ((isv) 196) /* Simulation                        */
#define ISV_PRIVATE  ((isv) 197) /* Private                           */
#define ISV_PUBLIC   ((isv) 198) /* Public                            */
#define ISV_BILLING  ((isv) 199) /* Billing                           */
#define ISV_MEMBER   ((isv) 201) /* Member                            */
#define ISV_MONITOR  ((isv) 202) /* Monitor                           */
#define ISV_EDITOR   ((isv) 203) /* Editor                            */
#define ISV_INDEXER  ((isv) 204) /* Indexer                           */
#define ISV_OBSERVER ((isv) 205) /* Observer                          */
#define ISV_LURKER   ((isv) 206) /* Lurker                            */
#define ISV_CONTRIBU ((isv) 207) /* Contributor                       */
#define ISV_RESPONDE ((isv) 208) /* Responder                         */
#define ISV_OWNER    ((isv) 209) /* Owner                             */
#define ISV_MASQUERA ((isv) 210) /* Masquerader                       */
#define ISV_COORDINA ((isv) 211) /* Coordinator                       */
#define ISV_REGULAR  ((isv) 241) /* Regular                           */
#define ISV_PENNAME  ((isv) 242) /* Penname                           */
#define ISV_ANONYMOU ((isv) 243) /* Anonymous                         */
#define ISV_TO       ((isv) 248) /* To                                */
#define ISV_TITLE    ((isv) 249) /* Title                             */
#define ISV_KEYS     ((isv) 250) /* Keywords                          */
#define ISV_PF_ENTER ((isv) 301) /* ENTER                             */
#define ISV_PF_HELP  ((isv) 302) /* HELP                              */
#define ISV_PF_CONFI ((isv) 303) /* CONFIRM                           */
#define ISV_PF_QUIT  ((isv) 304) /* QUIT                              */
#define ISV_PF_PROCE ((isv) 305) /* PROCESS                           */
#define ISV_PF_REPLY ((isv) 306) /* REPLY                             */
#define ISV_PF_PRINT ((isv) 307) /* PRINT                             */
#define ISV_PF_PREVI ((isv) 308) /* PREVIOUS                          */
#define ISV_PF_NEXT  ((isv) 309) /* NEXT                              */
#define ISV_PF_SCAN  ((isv) 310) /* SCAN                              */
#define ISV_PF_HPREV ((isv) 311) /* HPREVIOUS                         */
#define ISV_PF_HNEXT ((isv) 312) /* HNEXT                             */
#define ISV_PF_ABAND ((isv) 313) /* ABANDON                           */
#define ISV_PF_TOP   ((isv) 314) /* TOP                               */
#define ISV_PF_BOTTO ((isv) 315) /* BOTTOM                            */
#define ISV_PF_HOME  ((isv) 316) /* HOME                              */
#define ISV_PF_LEFT  ((isv) 317) /* LEFT                              */
#define ISV_PF_RIGHT ((isv) 318) /* RIGHT                             */
#define ISV_PF_CLEAR ((isv) 319) /* CLEAR                             */
#define ISV_PF_EDIT  ((isv) 320) /* EDIT                              */
#define ISV_PF_ESCAP ((isv) 321) /* ESCAPE                            */
#define ISV_ISV_MAX  ((isv) 399) /* End of ISV Table                  */
