/*+-------------------------------------------------------------------+
  |  <DOC>                                                            |
  |  <NAME>    OBJ_SYS Header                                         |
  |  <AUTHOR>  John L. Foster                                         |
  |  <DATE>    July 27, 1989                                          |
  |  <LEVEL>   OBJ                                                    |
  |  <PURPOSE> Define system level object-action routines.            |
  |  </DOC>                                                           |
  |  $EXTRACT                                                         |
  +-------------------------------------------------------------------+*/

extern sint cr_sys   () ; /* Create User & Group 0 for new database   */
extern sint md_sntfi () ; /* Interactively modify the SNTFI           */



/*                                                         $ENDEXTRACT */
