/*+-------------------------------------------------------------------+
  |  <DOC>                                                            |
  |  <NAME>    OBJ_TICK Header                                        |
  |  <AUTHOR>  John L. Foster                                         |
  |  <DATE>    Februaru 13, 1990                                      |
  |  <LEVEL>   OBJ                                                    |
  |  <PURPOSE> Define Ticket object routines and constants.           |
  |  </DOC>                                                           |
  +-------------------------------------------------------------------+*/
                          /*                                  $EXTRACT */
extern sint vw_tick  () ; /* Ticket objects                            */
extern sint cr_tick  () ;
extern sint sc_tick  () ;
extern sint fn_tick  () ;
extern sint md_tick  () ;
extern sint rc_tick  () ;
extern sint jn_tick  () ;
extern sint rm_tick  () ;
extern sint do_tick  () ;
extern sint lk_tick  () ;
extern sint gt_tick  () ;
extern sint rv_tick  () ;
extern sint or_tick  () ;
extern sint ex_tick  () ;
extern sint ab_tick  () ;


/*                                                         $ENDEXTRACT */
