/*+-------------------------------------------------------------------+*/
/*|                                                                   |*/
/*| :NAME.     OLD_BUG H                                              |*/
/*|                                                                   |*/
/*| :LEVEL.    DEBUG                                                  |*/
/*|                                                                   |*/
/*| :GLOBAL.                                                          |*/
/*|                                                                   |*/
/*| :PARAM.                                                           |*/
/*|                                                                   |*/
/*| :PURPOSE.  This dummy header is created just so that maker and    |*/
/*|            VCS will still put copies of outdated routines into    |*/
/*|            the DEBUG TXTLIB file.                                 |*/
/*|                                                                   |*/
/*| :OUTPUT.                                                          |*/
/*|                                                                   |*/
/*| :CALLS.                                                           |*/
/*|                                                                   |*/
/*| :ERRORS.                                                          |*/
/*|                                                                   |*/
/*| :LIMITS.                                                          |*/
/*|                                                                   |*/
/*| :MODS.     11_Aug_88   K.J.Walsh   Implemented.                   |*/
/*|                                                                   |*/
/*| :END.                                                             |*/
/*|                                                                   |*/
/*+-------------------------------------------------------------------+*/
/*|                                                                   |*/
/*|   $EXTRACT                                                        |*/
/*|                                                                   |*/
/*|   extern whatever D_gin();                                        |*/
/*|   extern whatever D_active();                                     |*/
/*|   extern whatever D_rxerr();                                      |*/
/*|                                                                   |*/
/*|   $ENDEXTRACT                                                     |*/
/*|                                                                   |*/
/*+-------------------------------------------------------------------+*/
