/*+-------------------------------------------------------------------+*/
/*|                                                                   |*/
/*|  :NAME.    OSK.h                                                  |*/
/*|                                                                   |*/
/*|  :LEVEL.   OSK                                                    |*/
/*|                                                                   |*/
/*|  :GLOBAL.                                                         |*/
/*|                                                                   |*/
/*|  :PARAM.                                                          |*/
/*|                                                                   |*/
/*|  :PURPOSE. Includes the two extern OSK header files.              |*/
/*|                                                                   |*/
/*|                                                                   |*/
/*|  :OUTPUT.                                                         |*/
/*|                                                                   |*/
/*|  :CALLS.                                                          |*/
/*|                                                                   |*/
/*|  :ERRORS.                                                         |*/
/*|                                                                   |*/
/*|  :LIMITS.                                                         |*/
/*|                                                                   |*/
/*|  :MODS.    08_Aug_86   K.J.Walsh   Written                        |*/
/*|                                                                   |*/
/*|  :END.                                                            |*/
/*|                                                                   |*/
/*+-------------------------------------------------------------------+*/

#ifndef OSK_H_INCLUDED

  #define OSK_H_INCLUDED

  #ifndef DEFS_H_INCLUDED

    error DEFS.H required by OSK.H

  #endif


  #include "osk_x.h"
  #include "osk_cset.h"

#endif
