/*+-------------------------------------------------------------------+*/
/*|                                                                   |*/
/*| :NAME.     P3_I H                                                 |*/
/*|                                                                   |*/
/*| :LEVEL.    PPP                                                    |*/
/*|                                                                   |*/
/*| :GLOBAL.                                                          |*/
/*|                                                                   |*/
/*| :PARAM.                                                           |*/
/*|                                                                   |*/
/*| :PURPOSE.  Does #includes of header files needed by most PPP      |*/
/*|            source files.  Also see P3_IO.H                        |*/
/*|                                                                   |*/
/*| :OUTPUT.                                                          |*/
/*|                                                                   |*/
/*| :CALLS.                                                           |*/
/*|                                                                   |*/
/*| :ERRORS.                                                          |*/
/*|                                                                   |*/
/*| :LIMITS.                                                          |*/
/*|                                                                   |*/
/*| :MODS.     30_Nov_88   K.J.Walsh   Implemented.                   |*/
/*|                                                                   |*/
/*| :END.                                                             |*/
/*|                                                                   |*/
/*+-------------------------------------------------------------------+*/

#ifndef P3_I_H_INCLUDED
#   define P3_I_H_INCLUDED
#   include <stdio.h>
#   include "defs.h"
#   include "debug.h"
#   include "p3_ii.h"
#endif
