/************************************************************************
 *  sgi.h     :  This header file supplies the necessity of routines    *
 *               for the indexing tree.                                 *
 *                                                                      *
 *                                                                      *
 * author     :  Fen-Chung Kung.  IBM-TEIES.                            *
 *                                                                      *
 * date       :  12-29-86.                                              *
 *                                                                      *
 ***********************************************************************/

/*$extract*/                  /* starting of MAKER */

extern sint   sgiadd(),       /* print routine which print out the     */

              sgi_ins(),
                              /* keys from the tree.                   */
              sgirpl(),

              sgi_rpl(),

              sgifnd(),

              sgi_fnd(),

              sgi_pos(),

              sgi_neg(),

              ptree(),

              sgidel();
/* $main runtree() */

 /* $endextract */
