/*+-------------------------------------------------------------------+*/
/*|                                                                   |*/
/*| :NAME.     STEST_I1 H                                             |*/
/*|                                                                   |*/
/*| :LEVEL.    STEST                                                  |*/
/*|                                                                   |*/
/*| :GLOBAL.                                                          |*/
/*|                                                                   |*/
/*| :PARAM.                                                           |*/
/*|                                                                   |*/
/*| :PURPOSE.  Provides extern's for some of STEST functions; also    |*/
/*|            for use with MAKER EXEC.                               |*/
/*|                                                                   |*/
/*| :OUTPUT.                                                          |*/
/*|                                                                   |*/
/*| :CALLS.                                                           |*/
/*|                                                                   |*/
/*| :ERRORS.                                                          |*/
/*|                                                                   |*/
/*| :LIMITS.   Only a partial file--MAKE could not handle a MAKE FILE |*/
/*|            big enough to process these routines and those also in |*/
/*|            STEST_I2.H and STEST_I3.H.                             |*/
/*|                                                                   |*/
/*| :MODS.     ??_???_??   K.J.Walsh   Implemented.                   |*/
/*|                                                                   |*/
/*| :MODS.     15_Feb_89   K.J.Walsh   Standardized.                  |*/
/*|                                                                   |*/
/*| :END.                                                             |*/
/*|                                                                   |*/
/*+-------------------------------------------------------------------+*/

#ifndef STEST_I1_H
#  define STEST_I1_H

   /* $EXTRACT $MAKER-PROTO */
   extern      stest01  (  void  )  ;
   extern      stest02  (  void  )  ;
   extern      stest03  (  void  )  ;
   extern      stest04  (  void  )  ;
   extern      stest05  (  void  )  ;
   extern      stest06  (  void  )  ;
   extern      stest07  (  void  )  ;
   extern      stest08  (  void  )  ;
   extern      stest09  (  void  )  ;
   extern      stest10  (  void  )  ;
   extern      stest11  (  void  )  ;
   extern      stest12  (  void  )  ;
   extern      stest13  (  void  )  ;
   extern      stest14  (  void  )  ;
   extern      stest15  (  void  )  ;
   extern      stest16  (  void  )  ;
   extern      stest17  (  void  )  ;
   extern      stest18  (  void  )  ;
   extern      stest19  (  void  )  ;
   extern      stest20  (  void  )  ;
   extern      stest21  (  void  )  ;
   extern      stest22  (  void  )  ;
   extern      stest23  (  void  )  ;
   extern      stest24  (  void  )  ;
   extern      stest25  (  void  )  ;
   extern      stest26  (  void  )  ;
   extern      stest27  (  void  )  ;
   extern      stest28  (  void  )  ;
   extern      stest29  (  void  )  ;
   extern      stest30  (  void  )  ;
   extern      stest31  (  void  )  ;
   extern      stest32  (  void  )  ;
   extern      stest33  (  void  )  ;
   extern      stest34  (  void  )  ;
   extern      stest35  (  void  )  ;
   extern      stest36  (  void  )  ;
   extern      stest37  (  void  )  ;
   extern      stest38  (  void  )  ;
   extern      stest39  (  void  )  ;
   extern      stest40  (  void  )  ;
   extern      stest41  (  void  )  ;
   extern      stest42  (  void  )  ;
   extern      stest43  (  void  )  ;
   extern      stest44  (  void  )  ;
   extern      stest45  (  void  )  ;
   extern      stest46  (  void  )  ;
   extern      stest47  (  void  )  ;
   extern      stest48  (  void  )  ;
   extern      stest49  (  void  )  ;
   /* $ENDEXTRACT */

   /*+----------------------------------------------------------------+*/
   /*| The above list is continued in STEST_I2 H so that MAKE doesn't |*/
   /*| get a stack overflow from the MAKE file (created by MAKER EXEC)|*/
   /*| being too big for it's little brain.                           |*/
   /*+----------------------------------------------------------------+*/

#endif
