/*+-------------------------------------------------------------------+*/
/*|                                                                   |*/
/*| :NAME.     STEST_I2 H                                             |*/
/*|                                                                   |*/
/*| :LEVEL.    STEST                                                  |*/
/*|                                                                   |*/
/*| :GLOBAL.                                                          |*/
/*|                                                                   |*/
/*| :PARAM.                                                           |*/
/*|                                                                   |*/
/*| :PURPOSE.  Provides extern's for some of STEST functions; also    |*/
/*|            for use with MAKER EXEC.                               |*/
/*|                                                                   |*/
/*| :OUTPUT.                                                          |*/
/*|                                                                   |*/
/*| :CALLS.                                                           |*/
/*|                                                                   |*/
/*| :ERRORS.                                                          |*/
/*|                                                                   |*/
/*| :LIMITS.   Only a partial file--MAKE could not handle a MAKE FILE |*/
/*|            big enough to process these routines and those also in |*/
/*|            STEST_I1.H and STEST_I3.H.                             |*/
/*|                                                                   |*/
/*| :MODS.     ??_???_??   K.J.Walsh   Implemented.                   |*/
/*|                                                                   |*/
/*| :MODS.     15_Feb_89   K.J.Walsh   Standardized.                  |*/
/*|                                                                   |*/
/*| :END.                                                             |*/
/*|                                                                   |*/
/*+-------------------------------------------------------------------+*/

#ifndef STEST_I2_H_INCLUDED

#   define STEST_I2_H_INCLUDED

   /* $EXTRACT $MAKER-PROTO */
   extern      stest    (  void  )  ;       /* $MAIN */
   extern      stest50  (  void  )  ;
   extern      stest51  (  void  )  ;
   extern      stest52  (  void  )  ;
   extern      stest53  (  void  )  ;
   extern      stest54  (  void  )  ;
   extern      stest55  (  void  )  ;
   extern      stest56  (  void  )  ;
   extern      stest57  (  void  )  ;
   extern      stest58  (  void  )  ;
   extern      stest59  (  void  )  ;
   extern      stest60  (  void  )  ;
   extern      stest61  (  void  )  ;
   extern      stest62  (  void  )  ;
   extern      stest63  (  void  )  ;
   extern      stest64  (  void  )  ;
   extern      stest65  (  void  )  ;
   extern      stest66  (  void  )  ;
   extern      stest67  (  void  )  ;
   extern      stest68  (  void  )  ;
   extern      stest69  (  void  )  ;
   extern      stest70  (  void  )  ;
   extern      stest71  (  void  )  ;
   extern      stest72  (  void  )  ;
   extern      stest73  (  void  )  ;
   extern      stest74  (  void  )  ;
   extern      stest75  (  void  )  ;
   extern      stest76  (  void  )  ;
   extern      stest77  (  void  )  ;
   extern      stest78  (  void  )  ;
   extern      stest79  (  void  )  ;
   extern      stest80  (  void  )  ;
   extern      stest81  (  void  )  ;
   extern      stest82  (  void  )  ;
   extern      stest83  (  void  )  ;
   extern      stest84  (  void  )  ;
   extern      stest85  (  void  )  ;
   extern      stest86  (  void  )  ;
   extern      stest87  (  void  )  ;
   extern      stest88  (  void  )  ;
   extern      stest89  (  void  )  ;
   extern      stest90  (  void  )  ;
   extern      stest91  (  void  )  ;
   extern      stest92  (  void  )  ;
   extern      stest93  (  void  )  ;
   extern      stest94  (  void  )  ;
   extern      stest95  (  void  )  ;
   extern      stest96  (  void  )  ;
   extern      stest97  (  void  )  ;
   extern      stest98  (  void  )  ;
   extern      stest99  (  void  )  ;
   /* $ENDEXTRACT */

#endif
