/*+-------------------------------------------------------------------+*/
/*|                                                                   |*/
/*| :NAME.     STR_I H                                                |*/
/*|                                                                   |*/
/*| :LEVEL.    STR                                                    |*/
/*|                                                                   |*/
/*| :GLOBAL.                                                          |*/
/*|                                                                   |*/
/*| :PARAM.                                                           |*/
/*|                                                                   |*/
/*| :PURPOSE.  Main internal-user string level header file.  Does     |*/
/*|            includes of files required internally by STR functions.|*/
/*|                                                                   |*/
/*| :OUTPUT.                                                          |*/
/*|                                                                   |*/
/*| :CALLS.                                                           |*/
/*|                                                                   |*/
/*| :ERRORS.                                                          |*/
/*|                                                                   |*/
/*| :LIMITS.                                                          |*/
/*|                                                                   |*/
/*| :MODS.     23_Mar_87   K.J.Walsh   Implemented.                   |*/
/*|                                                                   |*/
/*| :MODS.     15_Feb_89   K.J.Walsh   Standardized / Trimmed MODS.   |*/
/*|                                                                   |*/
/*| :END.                                                             |*/
/*|                                                                   |*/
/*+-------------------------------------------------------------------+*/

#ifndef STR_I_H_INCLUDED

#   define STR_I_H_INCLUDED

#   include "defs.h"
#   include "str_comm.h"
#   include "str_i_i.h"
#   include "str_x.h"
#   include "debug.h"

#endif
