/*+-------------------------------------------------------------------+
  |                                                                   |
  |  :NAME.    VDI Header                                             |
  |                                                                   |
  |  :AUTHOR.  John L. Foster                                         |
  |                                                                   |
  |  :DATE.    November 7, 1988                                       |
  |                                                                   |
  |  :LEVEL.   VDI                                                    |
  |                                                                   |
  |  :PURPOSE. Determine the proper inclusions for the VDI Level.     |
  |                                                                   |
  |  :END.                                                            |
  |                                                                   |
  +-------------------------------------------------------------------+*/
#ifndef VDI_H_INCLUDED

#define VDI_H_INCLUDED 1


#include "VDI_COMM.H"
#include "VDI_CDR.H"
#include "VDI_CON.H"
#include "VDI_I.H"
#include "VDI_I_I.H"
#include "VDI_X.H"

#endif
