/*********************************************************************

:NAME.    VDI_CON.H
:LEVEL.   VDI internal
:DATE.    September, 14, 1987
:AUTHOR.  Kenneth Liang

:PURPOSE. Defines constants, macros, and declarations used in Virtual
          Device Driver for IBM 3270 console.

:MODS.

:END.

 ***********************************************************************/


#include "gv_comm.h"
#include "vdi_comm.h"
#include "ibm3270.h"
#include "vdi_cdr.h"




