
/*********************************************************************

:NAME.        VDI_I.H
:LEVEL.       VDI  internal
:DATE.        June 11, 1987
:AUTHOR.      Kenneth Liang

:PURPOSE.     VDI functions header file for internal use. This file
              includes the following:

              1)   vdi_comm.h, the header file of definitions common
                   to both external and internal header files

              2)   vdi_i_i.h, the actual internal VDI header file


:MODS.

:END.

*********************************************************************/



#include "gv_comm.h"
#include "vdi_comm.h"
#include "vdi_i_i.h"
