/*********************************************************************

  :NAME.    VERSION H
  :AUTHOR.  John L. Foster
  :DATE.    March 25, 1988
  :PURPOSE. TEIES Version Control File. This must be included in TEIES
            main() and in any TEIES test routines that use the TM version
            control or the UI variable "%VERSION".

*********************************************************************/

#define VERSION_ID "071590"
#define RELEASE_ID   100
